import 'package:hive/hive.dart';

part 'note.g.dart'; // This will be generated by build_runner

@HiveType(typeId: 0) // Unique typeId for this model
class Note extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String title;

  @HiveField(2)
  final String content;

  Note({required this.id, required this.title, required this.content});

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Note && runtimeType == other.runtimeType && id == other.id;

  @override
  int get hashCode => id.hashCode;
}
